version: '2'

services:

  nats-streaming:
    image: library/nats-streaming:latest
    ports:
      - 4222:${N1_PORT}
      - 8222:${N2_PORT}

  postgres:
    image: library/postgres:12.5-alpine
    container_name: postgres-${APP_NAME}
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}